//! Generates the SteelMC → client registry-ID translation tables.
//!
//! `steel-provider` links a pinned SteelMC build that targets an older
//! Minecraft data version than the Minestom client that consumes its output.
//! Block-state IDs and biome IDs are wire-version specific, so a chunk palette
//! produced by SteelMC would be misinterpreted by the client's registries.
//!
//! This build script emits two tables into `$OUT_DIR`:
//!
//!  * `block_state_translation.rs` — `BLOCK_STATE_TRANSLATION[steel_state_id]`
//!    is the equivalent state ID in the client's data version.
//!
//!  * `biome_translation.rs` — `BIOME_TRANSLATION[steel_biome_id]` is the
//!    alphabetical rank of that biome's key in the client's biome set.
//!
//! Both tables are computed from the two `net.minestom:data` jars: the pinned
//! SteelMC's data version *is* the "from" version. Their paths are supplied by
//! the build via `MINESTOM_DATA_FROM_JAR` and `MINESTOM_DATA_TO_JAR`; when
//! either is missing the build fails. Every build goes through `mise run
//! build`, whose `minecraft-data` dependency resolves and exports both.

use std::collections::BTreeMap;
use std::env;
use std::fs;
use std::io::Read;
use std::path::{Path, PathBuf};

use serde::Deserialize;

fn main() {
    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-env-changed=MINESTOM_DATA_FROM_JAR");
    println!("cargo:rerun-if-env-changed=MINESTOM_DATA_TO_JAR");

    // The "from" side is SteelMC's data version; the "to" side is the client's,
    // discovered from the `minestom` dependency by Gradle so it can never drift
    // from `java-client/gradle/libs.versions.toml`. Both are passed as jar paths.
    let from = DataVersion::load("MINESTOM_DATA_FROM_JAR");
    let to = DataVersion::load("MINESTOM_DATA_TO_JAR");

    let out_dir = PathBuf::from(env::var_os("OUT_DIR").expect("OUT_DIR is set by cargo"));

    write_table(
        &out_dir.join("block_state_translation.rs"),
        "// @generated by build.rs -- do not edit.\n\
         //\n\
         // Maps SteelMC block-state IDs to the client's block-state IDs.\n",
        "BLOCK_STATE_TRANSLATION",
        &block_state_translation(&from, &to),
    );

    write_table(
        &out_dir.join("biome_translation.rs"),
        "// @generated by build.rs -- do not edit.\n\
         //\n\
         // Maps SteelMC biome IDs to the alphabetical rank of that biome's key\n\
         // in the client's biome set.\n",
        "BIOME_TRANSLATION",
        &biome_translation(&from, &to),
    );
}

/// Writes a `pub const NAME: [u16; N] = [ ... ];` table, 16 values per line.
fn write_table(path: &Path, header: &str, name: &str, values: &[u16]) {
    let mut out = String::with_capacity(header.len() + values.len() * 6 + 64);
    out.push_str(header);
    out.push('\n');
    out.push_str(&format!("pub static {name}: [u16; {}] = [\n", values.len()));
    for chunk in values.chunks(16) {
        out.push_str("    ");
        for (i, value) in chunk.iter().enumerate() {
            if i > 0 {
                out.push_str(", ");
            }
            out.push_str(&value.to_string());
        }
        out.push_str(",\n");
    }
    out.push_str("];\n");

    fs::write(path, out).unwrap_or_else(|e| panic!("failed to write {}: {e}", path.display()));
}

/// Maps each SteelMC (from) block-state ID to the corresponding (to) state ID.
///
/// Both versions enumerate a block's states in the same order, so the
/// property-state string present in `block.json` of one version names the same
/// state in the other. Matching by that string is immune to blocks being
/// inserted or appended between versions.
fn block_state_translation(from: &DataVersion, to: &DataVersion) -> Vec<u16> {
    let total = from.total_states();
    let mut mapping = vec![u16::MAX; total];

    for (key, from_block) in &from.blocks {
        let to_block = to.blocks.get(key).unwrap_or_else(|| {
            panic!(
                "block {key} exists in {} but not in {}",
                from.version, to.version
            )
        });
        for (state_key, from_state) in &from_block.states {
            let to_state = to_block.states.get(state_key).unwrap_or_else(|| {
                panic!(
                    "state {key}{state_key} exists in {} but not in {}",
                    from.version, to.version
                )
            });
            let index = from_state.state_id as usize;
            assert!(index < total, "from state ID {index} out of range");
            mapping[index] = to_state.state_id;
        }
    }

    assert!(
        mapping.iter().all(|&value| value != u16::MAX),
        "every from state ID must be mapped",
    );
    mapping
}

/// Maps each SteelMC biome ID (from-version alphabetical rank) to the
/// alphabetical rank of the same key in the to-version's biome set.
fn biome_translation(from: &DataVersion, to: &DataVersion) -> Vec<u16> {
    let to_ranks: BTreeMap<&str, u16> = to
        .biomes
        .iter()
        .map(|key| key.as_str())
        .collect::<Vec<_>>()
        .into_iter()
        .enumerate()
        .map(|(rank, key)| (key, rank as u16))
        .collect();

    from.biomes
        .iter()
        .map(|key| {
            *to_ranks.get(key.as_str()).unwrap_or_else(|| {
                panic!(
                    "biome {key} exists in {} but not in {}",
                    from.version, to.version
                )
            })
        })
        .collect()
}

/// One Minecraft data version, loaded from its `net.minestom:data` jar.
struct DataVersion {
    version: String,
    /// Block key (`minecraft:stone`) → block data, in registry order.
    blocks: BTreeMap<String, BlockData>,
    /// Biome keys in alphabetical order (which is registry order for SteelMC
    /// and is what the client's lookup uses).
    biomes: Vec<String>,
}

impl DataVersion {
    /// Loads a data version from the jar path in `env_var`. Fails if the
    /// variable is unset or the file is missing.
    fn load(env_var: &str) -> Self {
        let path = env::var_os(env_var).unwrap_or_else(|| {
            panic!(
                "{env_var} is not set. Run `mise run minecraft-data` before building, \
                 or set {env_var} to the net.minestom:data jar."
            )
        });
        let path = PathBuf::from(path);
        assert!(
            path.is_file(),
            "{env_var} points to a missing file: {}",
            path.display()
        );
        // e.g. data-26.3-rv1.jar -> 26.3-rv1
        let version = path
            .file_stem()
            .and_then(|stem| stem.to_str())
            .and_then(|stem| stem.strip_prefix("data-"))
            .unwrap_or("client")
            .to_string();
        Self::from_jar(path, version)
    }

    fn from_jar(jar: PathBuf, version: String) -> Self {
        println!("cargo:rerun-if-changed={}", jar.display());
        eprintln!(
            "steel-provider build: loading data {version} from {}",
            jar.display()
        );

        let blocks: BTreeMap<String, BlockData> =
            read_jar_json(&jar, "net/minestom/data/block.json");
        let biomes_raw: BTreeMap<String, serde_json::Value> =
            read_jar_json(&jar, "net/minestom/data/worldgen/biome.json");
        let mut biomes: Vec<String> = biomes_raw.keys().cloned().collect();
        biomes.sort();

        Self {
            version,
            blocks,
            biomes,
        }
    }

    fn total_states(&self) -> usize {
        self.blocks.values().map(|b| b.states.len()).sum()
    }
}

/// Reads and deserializes a JSON entry from a zip/jar.
fn read_jar_json<T: for<'de> Deserialize<'de>>(jar: &Path, entry: &str) -> T {
    let file =
        fs::File::open(jar).unwrap_or_else(|e| panic!("failed to open {}: {e}", jar.display()));
    let mut archive = zip::ZipArchive::new(file)
        .unwrap_or_else(|e| panic!("failed to read zip {}: {e}", jar.display()));
    let mut entry_reader = archive
        .by_name(entry)
        .unwrap_or_else(|e| panic!("{entry} not found in {}: {e}", jar.display()));
    let mut contents = String::new();
    entry_reader
        .read_to_string(&mut contents)
        .unwrap_or_else(|e| panic!("failed to read {entry}: {e}"));
    serde_json::from_str(&contents).unwrap_or_else(|e| panic!("failed to parse {entry}: {e}"))
}

/// One block's states from `block.json`, keyed by property-state string.
#[derive(Deserialize)]
struct BlockData {
    states: BTreeMap<String, BlockState>,
}

#[derive(Deserialize)]
struct BlockState {
    #[serde(rename = "stateId")]
    state_id: u16,
}
